// <auto-generated />
using System;
using HeThongPOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongPOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612205005_AddDummyDataFinal")]
    partial class AddDummyDataFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongPOS.Core.Entities.CaLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChenhLech")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoDuCuoiCaThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoDuDauCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("CA_LAM_VIEC", (string)null);
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonHangId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CHI_TIET_DON_HANG", (string)null);

                    b.HasData(
                        new
                        {
                            DonHangId = 1,
                            SanPhamId = 21,
                            DonGia = 102000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 1,
                            SanPhamId = 17,
                            DonGia = 90000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 1,
                            SanPhamId = 16,
                            DonGia = 78000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 2,
                            SanPhamId = 28,
                            DonGia = 45000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 3,
                            SanPhamId = 32,
                            DonGia = 82000m,
                            SoLuong = 2,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 3,
                            SanPhamId = 41,
                            DonGia = 120000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 4,
                            SanPhamId = 33,
                            DonGia = 102000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 5,
                            SanPhamId = 1,
                            DonGia = 71000m,
                            SoLuong = 2,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 5,
                            SanPhamId = 5,
                            DonGia = 179000m,
                            SoLuong = 2,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 5,
                            SanPhamId = 40,
                            DonGia = 47000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 5,
                            SanPhamId = 21,
                            DonGia = 72000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 6,
                            SanPhamId = 45,
                            DonGia = 97000m,
                            SoLuong = 2,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 7,
                            SanPhamId = 33,
                            DonGia = 18000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 8,
                            SanPhamId = 15,
                            DonGia = 58000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 8,
                            SanPhamId = 20,
                            DonGia = 183000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 8,
                            SanPhamId = 23,
                            DonGia = 108000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 8,
                            SanPhamId = 33,
                            DonGia = 172000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 9,
                            SanPhamId = 37,
                            DonGia = 38000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 9,
                            SanPhamId = 10,
                            DonGia = 41000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 9,
                            SanPhamId = 39,
                            DonGia = 30000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 9,
                            SanPhamId = 38,
                            DonGia = 175000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 10,
                            SanPhamId = 39,
                            DonGia = 55000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 10,
                            SanPhamId = 8,
                            DonGia = 134000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 10,
                            SanPhamId = 22,
                            DonGia = 90000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 10,
                            SanPhamId = 26,
                            DonGia = 118000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "",
                            TenDanhMuc = "Đồ ăn nhanh"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "",
                            TenDanhMuc = "Đồ uống"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "",
                            TenDanhMuc = "Gia vị"
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "",
                            TenDanhMuc = "Hóa mỹ phẩm"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChietKhau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("ThueVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("DON_HANG", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 1",
                            KhachHangId = 14,
                            MaDonHang = "DH202605290001",
                            NgayTao = new DateTime(2026, 5, 29, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(212),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 126000m,
                            TongTienHang = 0m,
                            TrangThai = 3
                        },
                        new
                        {
                            Id = 2,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 2",
                            KhachHangId = 4,
                            MaDonHang = "DH202605150002",
                            NgayTao = new DateTime(2026, 5, 15, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(281),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 482000m,
                            TongTienHang = 0m,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 3,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 3",
                            KhachHangId = 14,
                            MaDonHang = "DH202606120003",
                            NgayTao = new DateTime(2026, 6, 12, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(285),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 214000m,
                            TongTienHang = 0m,
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 4,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 4",
                            KhachHangId = 3,
                            MaDonHang = "DH202606060004",
                            NgayTao = new DateTime(2026, 6, 6, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(289),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 488000m,
                            TongTienHang = 0m,
                            TrangThai = 3
                        },
                        new
                        {
                            Id = 5,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 5",
                            KhachHangId = 1,
                            MaDonHang = "DH202605220005",
                            NgayTao = new DateTime(2026, 5, 22, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(292),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 463000m,
                            TongTienHang = 0m,
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 6,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 6",
                            KhachHangId = 8,
                            MaDonHang = "DH202605270006",
                            NgayTao = new DateTime(2026, 5, 27, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(296),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 204000m,
                            TongTienHang = 0m,
                            TrangThai = 3
                        },
                        new
                        {
                            Id = 7,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 7",
                            KhachHangId = 9,
                            MaDonHang = "DH202605150007",
                            NgayTao = new DateTime(2026, 5, 15, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(300),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 417000m,
                            TongTienHang = 0m,
                            TrangThai = 3
                        },
                        new
                        {
                            Id = 8,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 8",
                            KhachHangId = 3,
                            MaDonHang = "DH202605280008",
                            NgayTao = new DateTime(2026, 5, 28, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(303),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 237000m,
                            TongTienHang = 0m,
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 9,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 9",
                            KhachHangId = 11,
                            MaDonHang = "DH202605240009",
                            NgayTao = new DateTime(2026, 5, 24, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(306),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 482000m,
                            TongTienHang = 0m,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 10,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 10",
                            KhachHangId = 18,
                            MaDonHang = "DH202606070010",
                            NgayTao = new DateTime(2026, 6, 7, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(309),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 67000m,
                            TongTienHang = 0m,
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.GiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDichDoiTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhuongThucThanhToanId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("PhuongThucThanhToanId");

                    b.ToTable("GIAO_DICH", (string)null);
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiemTichLuy = 28,
                            Email = "khachhang1@example.com",
                            HoTen = "Khách hàng 1",
                            NgayTao = new DateTime(2026, 6, 12, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9957),
                            SoDienThoai = "0900000001"
                        },
                        new
                        {
                            Id = 2,
                            DiemTichLuy = 120,
                            Email = "khachhang2@example.com",
                            HoTen = "Khách hàng 2",
                            NgayTao = new DateTime(2026, 6, 11, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9967),
                            SoDienThoai = "0900000002"
                        },
                        new
                        {
                            Id = 3,
                            DiemTichLuy = 201,
                            Email = "khachhang3@example.com",
                            HoTen = "Khách hàng 3",
                            NgayTao = new DateTime(2026, 6, 10, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9977),
                            SoDienThoai = "0900000003"
                        },
                        new
                        {
                            Id = 4,
                            DiemTichLuy = 212,
                            Email = "khachhang4@example.com",
                            HoTen = "Khách hàng 4",
                            NgayTao = new DateTime(2026, 6, 9, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9981),
                            SoDienThoai = "0900000004"
                        },
                        new
                        {
                            Id = 5,
                            DiemTichLuy = 310,
                            Email = "khachhang5@example.com",
                            HoTen = "Khách hàng 5",
                            NgayTao = new DateTime(2026, 6, 8, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9986),
                            SoDienThoai = "0900000005"
                        },
                        new
                        {
                            Id = 6,
                            DiemTichLuy = 17,
                            Email = "khachhang6@example.com",
                            HoTen = "Khách hàng 6",
                            NgayTao = new DateTime(2026, 6, 7, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9990),
                            SoDienThoai = "0900000006"
                        },
                        new
                        {
                            Id = 7,
                            DiemTichLuy = 316,
                            Email = "khachhang7@example.com",
                            HoTen = "Khách hàng 7",
                            NgayTao = new DateTime(2026, 6, 6, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9993),
                            SoDienThoai = "0900000007"
                        },
                        new
                        {
                            Id = 8,
                            DiemTichLuy = 15,
                            Email = "khachhang8@example.com",
                            HoTen = "Khách hàng 8",
                            NgayTao = new DateTime(2026, 6, 5, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9996),
                            SoDienThoai = "0900000008"
                        },
                        new
                        {
                            Id = 9,
                            DiemTichLuy = 209,
                            Email = "khachhang9@example.com",
                            HoTen = "Khách hàng 9",
                            NgayTao = new DateTime(2026, 6, 4, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(4),
                            SoDienThoai = "0900000009"
                        },
                        new
                        {
                            Id = 10,
                            DiemTichLuy = 158,
                            Email = "khachhang10@example.com",
                            HoTen = "Khách hàng 10",
                            NgayTao = new DateTime(2026, 6, 3, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(10),
                            SoDienThoai = "0900000010"
                        },
                        new
                        {
                            Id = 11,
                            DiemTichLuy = 312,
                            Email = "khachhang11@example.com",
                            HoTen = "Khách hàng 11",
                            NgayTao = new DateTime(2026, 6, 2, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(13),
                            SoDienThoai = "0900000011"
                        },
                        new
                        {
                            Id = 12,
                            DiemTichLuy = 417,
                            Email = "khachhang12@example.com",
                            HoTen = "Khách hàng 12",
                            NgayTao = new DateTime(2026, 6, 1, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(15),
                            SoDienThoai = "0900000012"
                        },
                        new
                        {
                            Id = 13,
                            DiemTichLuy = 6,
                            Email = "khachhang13@example.com",
                            HoTen = "Khách hàng 13",
                            NgayTao = new DateTime(2026, 5, 31, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(19),
                            SoDienThoai = "0900000013"
                        },
                        new
                        {
                            Id = 14,
                            DiemTichLuy = 473,
                            Email = "khachhang14@example.com",
                            HoTen = "Khách hàng 14",
                            NgayTao = new DateTime(2026, 5, 30, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(22),
                            SoDienThoai = "0900000014"
                        },
                        new
                        {
                            Id = 15,
                            DiemTichLuy = 300,
                            Email = "khachhang15@example.com",
                            HoTen = "Khách hàng 15",
                            NgayTao = new DateTime(2026, 5, 29, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(24),
                            SoDienThoai = "0900000015"
                        },
                        new
                        {
                            Id = 16,
                            DiemTichLuy = 212,
                            Email = "khachhang16@example.com",
                            HoTen = "Khách hàng 16",
                            NgayTao = new DateTime(2026, 5, 28, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(27),
                            SoDienThoai = "0900000016"
                        },
                        new
                        {
                            Id = 17,
                            DiemTichLuy = 223,
                            Email = "khachhang17@example.com",
                            HoTen = "Khách hàng 17",
                            NgayTao = new DateTime(2026, 5, 27, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(31),
                            SoDienThoai = "0900000017"
                        },
                        new
                        {
                            Id = 18,
                            DiemTichLuy = 497,
                            Email = "khachhang18@example.com",
                            HoTen = "Khách hàng 18",
                            NgayTao = new DateTime(2026, 5, 26, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(35),
                            SoDienThoai = "0900000018"
                        },
                        new
                        {
                            Id = 19,
                            DiemTichLuy = 23,
                            Email = "khachhang19@example.com",
                            HoTen = "Khách hàng 19",
                            NgayTao = new DateTime(2026, 5, 25, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(37),
                            SoDienThoai = "0900000019"
                        },
                        new
                        {
                            Id = 20,
                            DiemTichLuy = 87,
                            Email = "khachhang20@example.com",
                            HoTen = "Khách hàng 20",
                            NgayTao = new DateTime(2026, 5, 24, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(40),
                            SoDienThoai = "0900000020"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("VaiTroId");

                    b.ToTable("NHAN_VIEN", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Nhân viên 1",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 174, DateTimeKind.Local).AddTicks(9795),
                            PasswordHash = "",
                            TrangThai = true,
                            Username = "",
                            VaiTroId = 1
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaVach")
                        .IsUnique();

                    b.ToTable("SAN_PHAM", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 367000m,
                            MaVach = "8930000000001",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(75),
                            TenSanPham = "Sản phẩm 1",
                            TonKho = 63,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 254000m,
                            MaVach = "8930000000002",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(84),
                            TenSanPham = "Sản phẩm 2",
                            TonKho = 78,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 188000m,
                            MaVach = "8930000000003",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(86),
                            TenSanPham = "Sản phẩm 3",
                            TonKho = 62,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 113000m,
                            MaVach = "8930000000004",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(88),
                            TenSanPham = "Sản phẩm 4",
                            TonKho = 24,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 440000m,
                            MaVach = "8930000000005",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(89),
                            TenSanPham = "Sản phẩm 5",
                            TonKho = 20,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 6,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 50000m,
                            MaVach = "8930000000006",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(92),
                            TenSanPham = "Sản phẩm 6",
                            TonKho = 99,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 7,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 349000m,
                            MaVach = "8930000000007",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(94),
                            TenSanPham = "Sản phẩm 7",
                            TonKho = 29,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 8,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 496000m,
                            MaVach = "8930000000008",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(95),
                            TenSanPham = "Sản phẩm 8",
                            TonKho = 76,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 9,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 276000m,
                            MaVach = "8930000000009",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(97),
                            TenSanPham = "Sản phẩm 9",
                            TonKho = 21,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 10,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 438000m,
                            MaVach = "8930000000010",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(99),
                            TenSanPham = "Sản phẩm 10",
                            TonKho = 48,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 11,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 231000m,
                            MaVach = "8930000000011",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(105),
                            TenSanPham = "Sản phẩm 11",
                            TonKho = 51,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 12,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 230000m,
                            MaVach = "8930000000012",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(107),
                            TenSanPham = "Sản phẩm 12",
                            TonKho = 20,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 13,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 145000m,
                            MaVach = "8930000000013",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(108),
                            TenSanPham = "Sản phẩm 13",
                            TonKho = 96,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 14,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 494000m,
                            MaVach = "8930000000014",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(110),
                            TenSanPham = "Sản phẩm 14",
                            TonKho = 20,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 15,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 368000m,
                            MaVach = "8930000000015",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(111),
                            TenSanPham = "Sản phẩm 15",
                            TonKho = 66,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 16,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 22000m,
                            MaVach = "8930000000016",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(112),
                            TenSanPham = "Sản phẩm 16",
                            TonKho = 16,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 17,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 336000m,
                            MaVach = "8930000000017",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(114),
                            TenSanPham = "Sản phẩm 17",
                            TonKho = 15,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 18,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 411000m,
                            MaVach = "8930000000018",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(116),
                            TenSanPham = "Sản phẩm 18",
                            TonKho = 15,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 19,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 238000m,
                            MaVach = "8930000000019",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(117),
                            TenSanPham = "Sản phẩm 19",
                            TonKho = 71,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 20,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 223000m,
                            MaVach = "8930000000020",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(119),
                            TenSanPham = "Sản phẩm 20",
                            TonKho = 55,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 21,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 247000m,
                            MaVach = "8930000000021",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(120),
                            TenSanPham = "Sản phẩm 21",
                            TonKho = 63,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 22,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 352000m,
                            MaVach = "8930000000022",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(121),
                            TenSanPham = "Sản phẩm 22",
                            TonKho = 27,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 23,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 426000m,
                            MaVach = "8930000000023",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(123),
                            TenSanPham = "Sản phẩm 23",
                            TonKho = 21,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 24,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 27000m,
                            MaVach = "8930000000024",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(124),
                            TenSanPham = "Sản phẩm 24",
                            TonKho = 74,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 25,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 246000m,
                            MaVach = "8930000000025",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(125),
                            TenSanPham = "Sản phẩm 25",
                            TonKho = 82,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 26,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 90000m,
                            MaVach = "8930000000026",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(126),
                            TenSanPham = "Sản phẩm 26",
                            TonKho = 62,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 27,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 86000m,
                            MaVach = "8930000000027",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(128),
                            TenSanPham = "Sản phẩm 27",
                            TonKho = 49,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 28,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 397000m,
                            MaVach = "8930000000028",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(129),
                            TenSanPham = "Sản phẩm 28",
                            TonKho = 86,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 29,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 495000m,
                            MaVach = "8930000000029",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(130),
                            TenSanPham = "Sản phẩm 29",
                            TonKho = 40,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 30,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 35000m,
                            MaVach = "8930000000030",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(132),
                            TenSanPham = "Sản phẩm 30",
                            TonKho = 63,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 31,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 355000m,
                            MaVach = "8930000000031",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(133),
                            TenSanPham = "Sản phẩm 31",
                            TonKho = 81,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 32,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 453000m,
                            MaVach = "8930000000032",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(134),
                            TenSanPham = "Sản phẩm 32",
                            TonKho = 46,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 33,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 154000m,
                            MaVach = "8930000000033",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(136),
                            TenSanPham = "Sản phẩm 33",
                            TonKho = 24,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 34,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 370000m,
                            MaVach = "8930000000034",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(138),
                            TenSanPham = "Sản phẩm 34",
                            TonKho = 79,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 35,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 450000m,
                            MaVach = "8930000000035",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(140),
                            TenSanPham = "Sản phẩm 35",
                            TonKho = 35,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 36,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 119000m,
                            MaVach = "8930000000036",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(141),
                            TenSanPham = "Sản phẩm 36",
                            TonKho = 81,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 37,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 211000m,
                            MaVach = "8930000000037",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(142),
                            TenSanPham = "Sản phẩm 37",
                            TonKho = 78,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 38,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 428000m,
                            MaVach = "8930000000038",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(144),
                            TenSanPham = "Sản phẩm 38",
                            TonKho = 35,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 39,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 174000m,
                            MaVach = "8930000000039",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(145),
                            TenSanPham = "Sản phẩm 39",
                            TonKho = 83,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 40,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 101000m,
                            MaVach = "8930000000040",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(146),
                            TenSanPham = "Sản phẩm 40",
                            TonKho = 95,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 41,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 318000m,
                            MaVach = "8930000000041",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(147),
                            TenSanPham = "Sản phẩm 41",
                            TonKho = 32,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 42,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 155000m,
                            MaVach = "8930000000042",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(149),
                            TenSanPham = "Sản phẩm 42",
                            TonKho = 55,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 43,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 71000m,
                            MaVach = "8930000000043",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(156),
                            TenSanPham = "Sản phẩm 43",
                            TonKho = 49,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 44,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 451000m,
                            MaVach = "8930000000044",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(157),
                            TenSanPham = "Sản phẩm 44",
                            TonKho = 19,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 45,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 238000m,
                            MaVach = "8930000000045",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(158),
                            TenSanPham = "Sản phẩm 45",
                            TonKho = 64,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 46,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 36000m,
                            MaVach = "8930000000046",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(160),
                            TenSanPham = "Sản phẩm 46",
                            TonKho = 10,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 47,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 216000m,
                            MaVach = "8930000000047",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(161),
                            TenSanPham = "Sản phẩm 47",
                            TonKho = 81,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 48,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 327000m,
                            MaVach = "8930000000048",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(163),
                            TenSanPham = "Sản phẩm 48",
                            TonKho = 49,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 49,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 440000m,
                            MaVach = "8930000000049",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(164),
                            TenSanPham = "Sản phẩm 49",
                            TonKho = 76,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 50,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 378000m,
                            MaVach = "8930000000050",
                            NgayTao = new DateTime(2026, 6, 13, 3, 50, 5, 175, DateTimeKind.Local).AddTicks(165),
                            TenSanPham = "Sản phẩm 50",
                            TonKho = 48,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "",
                            TenVaiTro = "Quản lý"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.CaLamViec", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.NhanVien", "NhanVien")
                        .WithMany("CaLamViecs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongPOS.Core.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongPOS.Core.Entities.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.GiaoDich", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DonHang", "DonHang")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongPOS.Core.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("PhuongThucThanhToanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.SanPham", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GiaoDichs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.Navigation("CaLamViecs");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("GiaoDichs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.VaiTro", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
