// <auto-generated />
using System;
using HeThongPOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongPOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611201937_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongPOS.Core.Entities.CaLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChenhLech")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoDuCuoiCaThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoDuDauCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("CA_LAM_VIEC", (string)null);
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonHangId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CHI_TIET_DON_HANG", (string)null);
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "",
                            TenDanhMuc = "Đồ ăn nhanh"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "",
                            TenDanhMuc = "Đồ uống"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "",
                            TenDanhMuc = "Gia vị"
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "",
                            TenDanhMuc = "Hóa mỹ phẩm"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChietKhau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("ThueVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("DON_HANG", (string)null);
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.GiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDichDoiTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhuongThucThanhToanId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("PhuongThucThanhToanId");

                    b.ToTable("GIAO_DICH", (string)null);
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 1",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000001"
                        },
                        new
                        {
                            Id = 1002,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 2",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000002"
                        },
                        new
                        {
                            Id = 1003,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 3",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000003"
                        },
                        new
                        {
                            Id = 1004,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 4",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000004"
                        },
                        new
                        {
                            Id = 1005,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 5",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000005"
                        },
                        new
                        {
                            Id = 1006,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 6",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000006"
                        },
                        new
                        {
                            Id = 1007,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 7",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000007"
                        },
                        new
                        {
                            Id = 1008,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 8",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000008"
                        },
                        new
                        {
                            Id = 1009,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 9",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000009"
                        },
                        new
                        {
                            Id = 1010,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 10",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000010"
                        },
                        new
                        {
                            Id = 1011,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 11",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000011"
                        },
                        new
                        {
                            Id = 1012,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 12",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000012"
                        },
                        new
                        {
                            Id = 1013,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 13",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000013"
                        },
                        new
                        {
                            Id = 1014,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 14",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000014"
                        },
                        new
                        {
                            Id = 1015,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 15",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000015"
                        },
                        new
                        {
                            Id = 1016,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 16",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000016"
                        },
                        new
                        {
                            Id = 1017,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 17",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000017"
                        },
                        new
                        {
                            Id = 1018,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 18",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000018"
                        },
                        new
                        {
                            Id = 1019,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 19",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000019"
                        },
                        new
                        {
                            Id = 1020,
                            DiemTichLuy = 0,
                            Email = "",
                            HoTen = "Khách hàng 20",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000020"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("VaiTroId");

                    b.ToTable("NHAN_VIEN", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Admin Tester",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "123",
                            TrangThai = true,
                            Username = "admin",
                            VaiTroId = 1
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenPhuongThuc = "Tiền mặt",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            TenPhuongThuc = "Thẻ ngân hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            TenPhuongThuc = "Chuyển khoản",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaVach")
                        .IsUnique();

                    b.ToTable("SAN_PHAM", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 11000m,
                            MaVach = "8930000000001",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 1",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1002,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 12000m,
                            MaVach = "8930000000002",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 2",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1003,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 13000m,
                            MaVach = "8930000000003",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 3",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1004,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 14000m,
                            MaVach = "8930000000004",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 4",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1005,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 15000m,
                            MaVach = "8930000000005",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 5",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1006,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 16000m,
                            MaVach = "8930000000006",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 6",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1007,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 17000m,
                            MaVach = "8930000000007",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 7",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1008,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 18000m,
                            MaVach = "8930000000008",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 8",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1009,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 19000m,
                            MaVach = "8930000000009",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 9",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1010,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 20000m,
                            MaVach = "8930000000010",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 10",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1011,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 21000m,
                            MaVach = "8930000000011",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 11",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1012,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 22000m,
                            MaVach = "8930000000012",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 12",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1013,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 23000m,
                            MaVach = "8930000000013",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 13",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1014,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 24000m,
                            MaVach = "8930000000014",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 14",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1015,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 25000m,
                            MaVach = "8930000000015",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 15",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1016,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 26000m,
                            MaVach = "8930000000016",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 16",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1017,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 27000m,
                            MaVach = "8930000000017",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 17",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1018,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 28000m,
                            MaVach = "8930000000018",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 18",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1019,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 29000m,
                            MaVach = "8930000000019",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 19",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1020,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 30000m,
                            MaVach = "8930000000020",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 20",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1021,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 31000m,
                            MaVach = "8930000000021",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 21",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1022,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 32000m,
                            MaVach = "8930000000022",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 22",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1023,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 33000m,
                            MaVach = "8930000000023",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 23",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1024,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 34000m,
                            MaVach = "8930000000024",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 24",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1025,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 35000m,
                            MaVach = "8930000000025",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 25",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1026,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 36000m,
                            MaVach = "8930000000026",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 26",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1027,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 37000m,
                            MaVach = "8930000000027",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 27",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1028,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 38000m,
                            MaVach = "8930000000028",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 28",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1029,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 39000m,
                            MaVach = "8930000000029",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 29",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1030,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 40000m,
                            MaVach = "8930000000030",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 30",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1031,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 41000m,
                            MaVach = "8930000000031",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 31",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1032,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 42000m,
                            MaVach = "8930000000032",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 32",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1033,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 43000m,
                            MaVach = "8930000000033",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 33",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1034,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 44000m,
                            MaVach = "8930000000034",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 34",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1035,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 45000m,
                            MaVach = "8930000000035",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 35",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1036,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 46000m,
                            MaVach = "8930000000036",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 36",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1037,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 47000m,
                            MaVach = "8930000000037",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 37",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1038,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 48000m,
                            MaVach = "8930000000038",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 38",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1039,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 49000m,
                            MaVach = "8930000000039",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 39",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1040,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 50000m,
                            MaVach = "8930000000040",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 40",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1041,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 51000m,
                            MaVach = "8930000000041",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 41",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1042,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 52000m,
                            MaVach = "8930000000042",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 42",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1043,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 53000m,
                            MaVach = "8930000000043",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 43",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1044,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 54000m,
                            MaVach = "8930000000044",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 44",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1045,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 55000m,
                            MaVach = "8930000000045",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 45",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1046,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 56000m,
                            MaVach = "8930000000046",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 46",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1047,
                            DanhMucId = 4,
                            DonViTinh = "",
                            GiaBan = 57000m,
                            MaVach = "8930000000047",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 47",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1048,
                            DanhMucId = 1,
                            DonViTinh = "",
                            GiaBan = 58000m,
                            MaVach = "8930000000048",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 48",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1049,
                            DanhMucId = 2,
                            DonViTinh = "",
                            GiaBan = 59000m,
                            MaVach = "8930000000049",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 49",
                            TonKho = 100,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 1050,
                            DanhMucId = 3,
                            DonViTinh = "",
                            GiaBan = 60000m,
                            MaVach = "8930000000050",
                            NgayTao = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenSanPham = "Sản phẩm mẫu 50",
                            TonKho = 100,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "",
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "",
                            TenVaiTro = "Cashier"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.CaLamViec", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.NhanVien", "NhanVien")
                        .WithMany("CaLamViecs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongPOS.Core.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongPOS.Core.Entities.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.GiaoDich", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DonHang", "DonHang")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongPOS.Core.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("PhuongThucThanhToanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.SanPham", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GiaoDichs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.Navigation("CaLamViecs");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("GiaoDichs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.VaiTro", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
