// <auto-generated />
using System;
using HeThongPOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongPOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613195750_AddPaymentDummyData")]
    partial class AddPaymentDummyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongPOS.Core.Entities.CaLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChenhLech")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoDuCuoiCaThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoDuDauCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("CA_LAM_VIEC", (string)null);
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DonHangId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CHI_TIET_DON_HANG", (string)null);

                    b.HasData(
                        new
                        {
                            DonHangId = 1,
                            SanPhamId = 17,
                            DonGia = 146000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 1,
                            SanPhamId = 33,
                            DonGia = 118000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 1,
                            SanPhamId = 36,
                            DonGia = 196000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 1,
                            SanPhamId = 3,
                            DonGia = 122000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 2,
                            SanPhamId = 43,
                            DonGia = 34000m,
                            SoLuong = 2,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 2,
                            SanPhamId = 38,
                            DonGia = 86000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 2,
                            SanPhamId = 5,
                            DonGia = 132000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 3,
                            SanPhamId = 3,
                            DonGia = 18000m,
                            SoLuong = 2,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 4,
                            SanPhamId = 35,
                            DonGia = 172000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 4,
                            SanPhamId = 15,
                            DonGia = 176000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 4,
                            SanPhamId = 16,
                            DonGia = 178000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 5,
                            SanPhamId = 30,
                            DonGia = 107000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 5,
                            SanPhamId = 19,
                            DonGia = 98000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 5,
                            SanPhamId = 41,
                            DonGia = 33000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 6,
                            SanPhamId = 47,
                            DonGia = 92000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 6,
                            SanPhamId = 34,
                            DonGia = 107000m,
                            SoLuong = 2,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 6,
                            SanPhamId = 48,
                            DonGia = 150000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 7,
                            SanPhamId = 27,
                            DonGia = 133000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 7,
                            SanPhamId = 4,
                            DonGia = 68000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 7,
                            SanPhamId = 49,
                            DonGia = 102000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 7,
                            SanPhamId = 9,
                            DonGia = 84000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 8,
                            SanPhamId = 25,
                            DonGia = 139000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 8,
                            SanPhamId = 35,
                            DonGia = 177000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 8,
                            SanPhamId = 48,
                            DonGia = 103000m,
                            SoLuong = 4,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 9,
                            SanPhamId = 24,
                            DonGia = 88000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 9,
                            SanPhamId = 4,
                            DonGia = 170000m,
                            SoLuong = 3,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 9,
                            SanPhamId = 13,
                            DonGia = 81000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 10,
                            SanPhamId = 47,
                            DonGia = 93000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        },
                        new
                        {
                            DonHangId = 10,
                            SanPhamId = 30,
                            DonGia = 136000m,
                            SoLuong = 1,
                            ThanhTien = 0m
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "",
                            TenDanhMuc = "Đồ ăn nhanh"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "",
                            TenDanhMuc = "Đồ uống"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "",
                            TenDanhMuc = "Gia vị"
                        },
                        new
                        {
                            Id = 4,
                            MoTa = "",
                            TenDanhMuc = "Hóa mỹ phẩm"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChietKhau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("ThueVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("DON_HANG", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 1",
                            KhachHangId = 7,
                            MaDonHang = "DH202605210001",
                            NgayTao = new DateTime(2026, 5, 21, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2584),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 204000m,
                            TongTienHang = 0m,
                            TrangThai = 3
                        },
                        new
                        {
                            Id = 2,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 2",
                            KhachHangId = 5,
                            MaDonHang = "DH202606050002",
                            NgayTao = new DateTime(2026, 6, 5, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2695),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 175000m,
                            TongTienHang = 0m,
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 3,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 3",
                            KhachHangId = 19,
                            MaDonHang = "DH202606010003",
                            NgayTao = new DateTime(2026, 6, 1, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2712),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 174000m,
                            TongTienHang = 0m,
                            TrangThai = 2
                        },
                        new
                        {
                            Id = 4,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 4",
                            KhachHangId = 2,
                            MaDonHang = "DH202605170004",
                            NgayTao = new DateTime(2026, 5, 17, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2726),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 321000m,
                            TongTienHang = 0m,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 5,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 5",
                            KhachHangId = 1,
                            MaDonHang = "DH202606020005",
                            NgayTao = new DateTime(2026, 6, 2, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2740),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 474000m,
                            TongTienHang = 0m,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 6,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 6",
                            KhachHangId = 10,
                            MaDonHang = "DH202605170006",
                            NgayTao = new DateTime(2026, 5, 17, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2754),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 262000m,
                            TongTienHang = 0m,
                            TrangThai = 3
                        },
                        new
                        {
                            Id = 7,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 7",
                            KhachHangId = 2,
                            MaDonHang = "DH202605300007",
                            NgayTao = new DateTime(2026, 5, 30, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2768),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 160000m,
                            TongTienHang = 0m,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 8,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 8",
                            KhachHangId = 7,
                            MaDonHang = "DH202605180008",
                            NgayTao = new DateTime(2026, 5, 18, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2781),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 231000m,
                            TongTienHang = 0m,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 9,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 9",
                            KhachHangId = 12,
                            MaDonHang = "DH202606020009",
                            NgayTao = new DateTime(2026, 6, 2, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2796),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 406000m,
                            TongTienHang = 0m,
                            TrangThai = 3
                        },
                        new
                        {
                            Id = 10,
                            ChietKhau = 0m,
                            GhiChu = "Đơn hàng mẫu 10",
                            KhachHangId = 19,
                            MaDonHang = "DH202606030010",
                            NgayTao = new DateTime(2026, 6, 3, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2824),
                            NhanVienId = 1,
                            ThueVAT = 0m,
                            TongThanhToan = 476000m,
                            TongTienHang = 0m,
                            TrangThai = 2
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.GiaoDich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDichDoiTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhuongThucThanhToanId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("PhuongThucThanhToanId");

                    b.ToTable("GIAO_DICH", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonHangId = 1,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 5, 16, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3071),
                            PhuongThucThanhToanId = 1,
                            SoTien = 126000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 2,
                            DonHangId = 2,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 5, 30, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3076),
                            PhuongThucThanhToanId = 1,
                            SoTien = 482000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 3,
                            DonHangId = 3,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 6, 13, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3078),
                            PhuongThucThanhToanId = 2,
                            SoTien = 214000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 4,
                            DonHangId = 4,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 6, 8, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3081),
                            PhuongThucThanhToanId = 1,
                            SoTien = 488000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 5,
                            DonHangId = 5,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 5, 23, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3083),
                            PhuongThucThanhToanId = 2,
                            SoTien = 463000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 6,
                            DonHangId = 6,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 5, 18, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3087),
                            PhuongThucThanhToanId = 1,
                            SoTien = 204000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 7,
                            DonHangId = 7,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 5, 30, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3089),
                            PhuongThucThanhToanId = 3,
                            SoTien = 417000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 8,
                            DonHangId = 8,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 5, 17, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3092),
                            PhuongThucThanhToanId = 2,
                            SoTien = 237000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 9,
                            DonHangId = 9,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 5, 21, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3094),
                            PhuongThucThanhToanId = 1,
                            SoTien = 482000m,
                            TrangThai = "SUCCESS"
                        },
                        new
                        {
                            Id = 10,
                            DonHangId = 10,
                            MaGiaoDichDoiTac = "",
                            NgayGiaoDich = new DateTime(2026, 6, 7, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(3108),
                            PhuongThucThanhToanId = 1,
                            SoTien = 67000m,
                            TrangThai = "SUCCESS"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiemTichLuy = 466,
                            Email = "khachhang1@example.com",
                            HoTen = "Khách hàng 1",
                            NgayTao = new DateTime(2026, 6, 13, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1812),
                            SoDienThoai = "0900000001"
                        },
                        new
                        {
                            Id = 2,
                            DiemTichLuy = 401,
                            Email = "khachhang2@example.com",
                            HoTen = "Khách hàng 2",
                            NgayTao = new DateTime(2026, 6, 12, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1840),
                            SoDienThoai = "0900000002"
                        },
                        new
                        {
                            Id = 3,
                            DiemTichLuy = 350,
                            Email = "khachhang3@example.com",
                            HoTen = "Khách hàng 3",
                            NgayTao = new DateTime(2026, 6, 11, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1860),
                            SoDienThoai = "0900000003"
                        },
                        new
                        {
                            Id = 4,
                            DiemTichLuy = 112,
                            Email = "khachhang4@example.com",
                            HoTen = "Khách hàng 4",
                            NgayTao = new DateTime(2026, 6, 10, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1888),
                            SoDienThoai = "0900000004"
                        },
                        new
                        {
                            Id = 5,
                            DiemTichLuy = 322,
                            Email = "khachhang5@example.com",
                            HoTen = "Khách hàng 5",
                            NgayTao = new DateTime(2026, 6, 9, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1901),
                            SoDienThoai = "0900000005"
                        },
                        new
                        {
                            Id = 6,
                            DiemTichLuy = 195,
                            Email = "khachhang6@example.com",
                            HoTen = "Khách hàng 6",
                            NgayTao = new DateTime(2026, 6, 8, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1917),
                            SoDienThoai = "0900000006"
                        },
                        new
                        {
                            Id = 7,
                            DiemTichLuy = 125,
                            Email = "khachhang7@example.com",
                            HoTen = "Khách hàng 7",
                            NgayTao = new DateTime(2026, 6, 7, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1953),
                            SoDienThoai = "0900000007"
                        },
                        new
                        {
                            Id = 8,
                            DiemTichLuy = 216,
                            Email = "khachhang8@example.com",
                            HoTen = "Khách hàng 8",
                            NgayTao = new DateTime(2026, 6, 6, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1971),
                            SoDienThoai = "0900000008"
                        },
                        new
                        {
                            Id = 9,
                            DiemTichLuy = 304,
                            Email = "khachhang9@example.com",
                            HoTen = "Khách hàng 9",
                            NgayTao = new DateTime(2026, 6, 5, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1985),
                            SoDienThoai = "0900000009"
                        },
                        new
                        {
                            Id = 10,
                            DiemTichLuy = 122,
                            Email = "khachhang10@example.com",
                            HoTen = "Khách hàng 10",
                            NgayTao = new DateTime(2026, 6, 4, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2002),
                            SoDienThoai = "0900000010"
                        },
                        new
                        {
                            Id = 11,
                            DiemTichLuy = 208,
                            Email = "khachhang11@example.com",
                            HoTen = "Khách hàng 11",
                            NgayTao = new DateTime(2026, 6, 3, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2014),
                            SoDienThoai = "0900000011"
                        },
                        new
                        {
                            Id = 12,
                            DiemTichLuy = 169,
                            Email = "khachhang12@example.com",
                            HoTen = "Khách hàng 12",
                            NgayTao = new DateTime(2026, 6, 2, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2029),
                            SoDienThoai = "0900000012"
                        },
                        new
                        {
                            Id = 13,
                            DiemTichLuy = 326,
                            Email = "khachhang13@example.com",
                            HoTen = "Khách hàng 13",
                            NgayTao = new DateTime(2026, 6, 1, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2043),
                            SoDienThoai = "0900000013"
                        },
                        new
                        {
                            Id = 14,
                            DiemTichLuy = 117,
                            Email = "khachhang14@example.com",
                            HoTen = "Khách hàng 14",
                            NgayTao = new DateTime(2026, 5, 31, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2055),
                            SoDienThoai = "0900000014"
                        },
                        new
                        {
                            Id = 15,
                            DiemTichLuy = 472,
                            Email = "khachhang15@example.com",
                            HoTen = "Khách hàng 15",
                            NgayTao = new DateTime(2026, 5, 30, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2067),
                            SoDienThoai = "0900000015"
                        },
                        new
                        {
                            Id = 16,
                            DiemTichLuy = 353,
                            Email = "khachhang16@example.com",
                            HoTen = "Khách hàng 16",
                            NgayTao = new DateTime(2026, 5, 29, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2083),
                            SoDienThoai = "0900000016"
                        },
                        new
                        {
                            Id = 17,
                            DiemTichLuy = 98,
                            Email = "khachhang17@example.com",
                            HoTen = "Khách hàng 17",
                            NgayTao = new DateTime(2026, 5, 28, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2096),
                            SoDienThoai = "0900000017"
                        },
                        new
                        {
                            Id = 18,
                            DiemTichLuy = 180,
                            Email = "khachhang18@example.com",
                            HoTen = "Khách hàng 18",
                            NgayTao = new DateTime(2026, 5, 27, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2110),
                            SoDienThoai = "0900000018"
                        },
                        new
                        {
                            Id = 19,
                            DiemTichLuy = 295,
                            Email = "khachhang19@example.com",
                            HoTen = "Khách hàng 19",
                            NgayTao = new DateTime(2026, 5, 26, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2122),
                            SoDienThoai = "0900000019"
                        },
                        new
                        {
                            Id = 20,
                            DiemTichLuy = 496,
                            Email = "khachhang20@example.com",
                            HoTen = "Khách hàng 20",
                            NgayTao = new DateTime(2026, 5, 25, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2137),
                            SoDienThoai = "0900000020"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("VaiTroId");

                    b.ToTable("NHAN_VIEN", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Nhân viên 1",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(1565),
                            PasswordHash = "",
                            TrangThai = true,
                            Username = "",
                            VaiTroId = 1
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PhuongThucThanhToans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenPhuongThuc = "Tiền mặt",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            TenPhuongThuc = "Thẻ ngân hàng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            TenPhuongThuc = "Chuyển khoản",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaVach")
                        .IsUnique();

                    b.ToTable("SAN_PHAM", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 416000m,
                            MaVach = "8930000000001",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2252),
                            TenSanPham = "Sản phẩm 1",
                            TonKho = 81,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 150000m,
                            MaVach = "8930000000002",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2272),
                            TenSanPham = "Sản phẩm 2",
                            TonKho = 75,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 499000m,
                            MaVach = "8930000000003",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2277),
                            TenSanPham = "Sản phẩm 3",
                            TonKho = 94,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 265000m,
                            MaVach = "8930000000004",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2280),
                            TenSanPham = "Sản phẩm 4",
                            TonKho = 22,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 479000m,
                            MaVach = "8930000000005",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2283),
                            TenSanPham = "Sản phẩm 5",
                            TonKho = 83,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 6,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 248000m,
                            MaVach = "8930000000006",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2287),
                            TenSanPham = "Sản phẩm 6",
                            TonKho = 59,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 7,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 327000m,
                            MaVach = "8930000000007",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2290),
                            TenSanPham = "Sản phẩm 7",
                            TonKho = 18,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 8,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 324000m,
                            MaVach = "8930000000008",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2304),
                            TenSanPham = "Sản phẩm 8",
                            TonKho = 71,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 9,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 66000m,
                            MaVach = "8930000000009",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2306),
                            TenSanPham = "Sản phẩm 9",
                            TonKho = 14,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 10,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 325000m,
                            MaVach = "8930000000010",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2310),
                            TenSanPham = "Sản phẩm 10",
                            TonKho = 22,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 11,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 148000m,
                            MaVach = "8930000000011",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2314),
                            TenSanPham = "Sản phẩm 11",
                            TonKho = 66,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 12,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 471000m,
                            MaVach = "8930000000012",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2317),
                            TenSanPham = "Sản phẩm 12",
                            TonKho = 18,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 13,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 53000m,
                            MaVach = "8930000000013",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2320),
                            TenSanPham = "Sản phẩm 13",
                            TonKho = 39,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 14,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 125000m,
                            MaVach = "8930000000014",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2323),
                            TenSanPham = "Sản phẩm 14",
                            TonKho = 50,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 15,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 138000m,
                            MaVach = "8930000000015",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2325),
                            TenSanPham = "Sản phẩm 15",
                            TonKho = 93,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 16,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 139000m,
                            MaVach = "8930000000016",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2328),
                            TenSanPham = "Sản phẩm 16",
                            TonKho = 40,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 17,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 373000m,
                            MaVach = "8930000000017",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2330),
                            TenSanPham = "Sản phẩm 17",
                            TonKho = 27,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 18,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 316000m,
                            MaVach = "8930000000018",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2334),
                            TenSanPham = "Sản phẩm 18",
                            TonKho = 42,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 19,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 319000m,
                            MaVach = "8930000000019",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2337),
                            TenSanPham = "Sản phẩm 19",
                            TonKho = 93,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 20,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 51000m,
                            MaVach = "8930000000020",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2339),
                            TenSanPham = "Sản phẩm 20",
                            TonKho = 20,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 21,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 115000m,
                            MaVach = "8930000000021",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2342),
                            TenSanPham = "Sản phẩm 21",
                            TonKho = 89,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 22,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 268000m,
                            MaVach = "8930000000022",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2345),
                            TenSanPham = "Sản phẩm 22",
                            TonKho = 88,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 23,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 148000m,
                            MaVach = "8930000000023",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2347),
                            TenSanPham = "Sản phẩm 23",
                            TonKho = 98,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 24,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 284000m,
                            MaVach = "8930000000024",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2350),
                            TenSanPham = "Sản phẩm 24",
                            TonKho = 91,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 25,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 329000m,
                            MaVach = "8930000000025",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2353),
                            TenSanPham = "Sản phẩm 25",
                            TonKho = 12,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 26,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 444000m,
                            MaVach = "8930000000026",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2355),
                            TenSanPham = "Sản phẩm 26",
                            TonKho = 68,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 27,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 417000m,
                            MaVach = "8930000000027",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2358),
                            TenSanPham = "Sản phẩm 27",
                            TonKho = 29,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 28,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 349000m,
                            MaVach = "8930000000028",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2360),
                            TenSanPham = "Sản phẩm 28",
                            TonKho = 33,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 29,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 433000m,
                            MaVach = "8930000000029",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2363),
                            TenSanPham = "Sản phẩm 29",
                            TonKho = 22,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 30,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 45000m,
                            MaVach = "8930000000030",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2366),
                            TenSanPham = "Sản phẩm 30",
                            TonKho = 56,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 31,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 450000m,
                            MaVach = "8930000000031",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2368),
                            TenSanPham = "Sản phẩm 31",
                            TonKho = 13,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 32,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 360000m,
                            MaVach = "8930000000032",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2371),
                            TenSanPham = "Sản phẩm 32",
                            TonKho = 72,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 33,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 433000m,
                            MaVach = "8930000000033",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2373),
                            TenSanPham = "Sản phẩm 33",
                            TonKho = 20,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 34,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 243000m,
                            MaVach = "8930000000034",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2377),
                            TenSanPham = "Sản phẩm 34",
                            TonKho = 40,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 35,
                            DanhMucId = 2,
                            DonViTinh = "Hộp",
                            GiaBan = 69000m,
                            MaVach = "8930000000035",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2379),
                            TenSanPham = "Sản phẩm 35",
                            TonKho = 45,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 36,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 112000m,
                            MaVach = "8930000000036",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2382),
                            TenSanPham = "Sản phẩm 36",
                            TonKho = 60,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 37,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 195000m,
                            MaVach = "8930000000037",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2385),
                            TenSanPham = "Sản phẩm 37",
                            TonKho = 48,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 38,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 279000m,
                            MaVach = "8930000000038",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2387),
                            TenSanPham = "Sản phẩm 38",
                            TonKho = 17,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 39,
                            DanhMucId = 3,
                            DonViTinh = "Hộp",
                            GiaBan = 480000m,
                            MaVach = "8930000000039",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2400),
                            TenSanPham = "Sản phẩm 39",
                            TonKho = 70,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 40,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 313000m,
                            MaVach = "8930000000040",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2403),
                            TenSanPham = "Sản phẩm 40",
                            TonKho = 67,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 41,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 369000m,
                            MaVach = "8930000000041",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2405),
                            TenSanPham = "Sản phẩm 41",
                            TonKho = 63,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 42,
                            DanhMucId = 2,
                            DonViTinh = "Cái",
                            GiaBan = 394000m,
                            MaVach = "8930000000042",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2408),
                            TenSanPham = "Sản phẩm 42",
                            TonKho = 45,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 43,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 110000m,
                            MaVach = "8930000000043",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2410),
                            TenSanPham = "Sản phẩm 43",
                            TonKho = 38,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 44,
                            DanhMucId = 4,
                            DonViTinh = "Cái",
                            GiaBan = 439000m,
                            MaVach = "8930000000044",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2413),
                            TenSanPham = "Sản phẩm 44",
                            TonKho = 51,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 45,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 100000m,
                            MaVach = "8930000000045",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2415),
                            TenSanPham = "Sản phẩm 45",
                            TonKho = 47,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 46,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 352000m,
                            MaVach = "8930000000046",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2418),
                            TenSanPham = "Sản phẩm 46",
                            TonKho = 76,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 47,
                            DanhMucId = 4,
                            DonViTinh = "Hộp",
                            GiaBan = 306000m,
                            MaVach = "8930000000047",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2421),
                            TenSanPham = "Sản phẩm 47",
                            TonKho = 88,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 48,
                            DanhMucId = 1,
                            DonViTinh = "Cái",
                            GiaBan = 241000m,
                            MaVach = "8930000000048",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2423),
                            TenSanPham = "Sản phẩm 48",
                            TonKho = 28,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 49,
                            DanhMucId = 1,
                            DonViTinh = "Hộp",
                            GiaBan = 310000m,
                            MaVach = "8930000000049",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2426),
                            TenSanPham = "Sản phẩm 49",
                            TonKho = 35,
                            TrangThai = true
                        },
                        new
                        {
                            Id = 50,
                            DanhMucId = 3,
                            DonViTinh = "Cái",
                            GiaBan = 95000m,
                            MaVach = "8930000000050",
                            NgayTao = new DateTime(2026, 6, 14, 2, 57, 47, 815, DateTimeKind.Local).AddTicks(2428),
                            TenSanPham = "Sản phẩm 50",
                            TonKho = 11,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "",
                            TenVaiTro = "Quản lý"
                        });
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.CaLamViec", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.NhanVien", "NhanVien")
                        .WithMany("CaLamViecs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongPOS.Core.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongPOS.Core.Entities.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.GiaoDich", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DonHang", "DonHang")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongPOS.Core.Entities.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("GiaoDichs")
                        .HasForeignKey("PhuongThucThanhToanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.SanPham", b =>
                {
                    b.HasOne("HeThongPOS.Core.Entities.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GiaoDichs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.NhanVien", b =>
                {
                    b.Navigation("CaLamViecs");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.PhuongThucThanhToan", b =>
                {
                    b.Navigation("GiaoDichs");
                });

            modelBuilder.Entity("HeThongPOS.Core.Entities.VaiTro", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
